trigger:
- main

pool:
  name: 'Default'
variables:
  RESOURCE_GROUP: 'rg-aca-app-bicep'
  LOCATION: 'westeurope'
  DEPLOYMENT_NAME: 'aca-demo-bicep'
  TEMPLATE_FILE: 'main.bicep'

stages:
- stage: Deploy
  jobs:
  - job: DeployInfrastructure
    displayName: 'Deploy Infrastructure'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'SkyNetLab'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "##[section]Creating Resource Group"
          az group create --name $(RESOURCE_GROUP) --location $(LOCATION)
          echo "##[section]Previewing Deployment"
          az deployment group what-if --name $(DEPLOYMENT_NAME) --resource-group $(RESOURCE_GROUP) --template-file $(TEMPLATE_FILE)
          echo "##[section]Applying Deployment"
          az deployment group create --name $(DEPLOYMENT_NAME) --resource-group $(RESOURCE_GROUP) --template-file $(TEMPLATE_FILE)